# Generated by Django 4.0.3 on 2022-03-08 05:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.FloatField()),
                ('emissao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('data_receber', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas_receber.statuscontareceber')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta à Receber',
                'verbose_name_plural': 'Contas à Receber',
                'ordering': ['id'],
            },
        ),
    ]
