# Generated by Django 4.0.3 on 2022-03-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_pagar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='valor',
            field=models.FloatField(),
        ),
    ]
