# Generated by Django 4.0.3 on 2022-03-08 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas_pagar', '0002_alter_contapagar_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contapagar',
            old_name='date_cadastro',
            new_name='data_cadastro',
        ),
    ]
