# Generated by Django 4.0.3 on 2022-03-08 02:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas_pagar', '0003_rename_date_cadastro_contapagar_data_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='contapagar',
            old_name='data_cadastro',
            new_name='data_vencimento',
        ),
        migrations.AddField(
            model_name='contapagar',
            name='emissao',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas_pagar.statuscontapagar'),
        ),
    ]
