# Generated by Django 4.0.3 on 2022-03-08 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas_pagar', '0004_statuscontapagar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contapagar',
            options={'ordering': ['id'], 'verbose_name': 'Conta à Pagar', 'verbose_name_plural': 'Contas à Pagar'},
        ),
        migrations.AlterModelOptions(
            name='statuscontapagar',
            options={'ordering': ['nome'], 'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
    ]
